image: maven:3-jdk-11

variables:
  POSTGRES_HOST: docker
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

services:
  - postgres:latest
  
stages:
  - build
  - test
  - deploy

build-backend:
  stage: build
  script:
    - cd backend && mvn clean install -DskipTests
  tags: [runner]
  only:
    - dev
    - master

build-frontend:
  image: node:lts
  stage: build
  script:
    - cd frontend && npm install && npx ng build
  tags: [runner]
  only:
    - dev
    - master

test-backend:
  stage: test
  script:
    - cd backend && mvn test
  tags: [runner]
  only:
    - dev
    - master

deploy-backend:
  stage: deploy
  script:
    - cd backend && mvn clean install -DskipTests
    - mvn $MAVEN_CLI_OPTS  org.springframework.boot:spring-boot-maven-plugin:run
  tags: [runner]
  only:
    - dev
    - master

deploy-frontend:
  image: node:lts
  stage: deploy
  script:
    - cd frontend && npm start
    - cd frontend && npm install && npm install -g angular-cli
    - npm start
  tags: [runner]
  only:
    - dev
    - master